### ISSUE TITLE
READme não indica as ligações necessárias para o projeto

### ISSUE THREAD

**Issue by eduardomarossi** [slimkaki/APS1-Embarcados#1]
Por favor indicar quais ligações devem ser feitas (buzzer, placa OLED).

**Comment by heliopn** [comment]
Acabei ficando nervoso pra enviar logo o projeto que ja estava em atraso e esqueci de enviar o ReadMe. Issue resolvido.

**Comment by heliopn** [comment]
Peguei o template do ReadMe de um outro projeto Du. Mas alterei pra que ficasse coerente com essa entrega, tem algum problema? Se quiser posso fazer um do zero.
