### ISSUE TITLE
Duas funções para tocar

### ISSUE THREAD

**Issue by eduardomarossi** [slimkaki/APS1-Embarcados#3]
https://github.com/slimkaki/APS1-Embarcados/blob/f4328b2bc7f28c5860b09de09f1802193f1fd6cd/src/main.c#L165-L221

Existe algum motivo para uso de duas? Não seria possível juntar em uma?

**Comment by heliopn** [comment]
O motivo foi unicamente tentar diferenciar quando e tocado uma musica do pause e quando 'e uma musica do zero. Na hora na~o consegui pensar em outra forma de fazer, mas posso resolver isso agora.
