### ISSUE TITLE
Criar um define para cada prioridade 

### ISSUE THREAD

**Issue by eduardomarossi** [slimkaki/APS1-Embarcados#4]
https://github.com/slimkaki/APS1-Embarcados/blob/f4328b2bc7f28c5860b09de09f1802193f1fd6cd/src/main.c#L297-L304

Exemplo
```
// (Colocar este define junto com os outros do botão)
#define BUT2_PRIORITY 6

NVIC_SetPriority(BUT2_PIO_ID, BUT2_PRIORITY);
```

Vantagens:
- Fica explicito junto com as demais configurações do botão, permitindo fácil alteração da prioridade se necessário.
- Evita número "mágico" no meio do código, ficando bem óbvio o que se trata (código se auto documenta).

**Comment by heliopn** [comment]
Ok, Obrigado pelo comentario! Ja irei fazer a alteracao
