### ISSUE TITLE
Boas práticas de formatação

### ISSUE THREAD

**Issue by eduardomarossi** [slimkaki/APS1-Embarcados#5]
https://github.com/slimkaki/APS1-Embarcados/blob/f4328b2bc7f28c5860b09de09f1802193f1fd6cd/src/main.c#L355-L411

Apesar de não está errado.

Tem momentos no código que após um if ou else, não há espaços para as chaves { e e outros momentos há. Assim como inconsistência em geral da formatação do código (condições do if sem espaço, ex: a==b)

O recomendado é seguir um padrão de estilo de codificação ("coding style"). Para C, a maioria é similar.

Segue alguns para sua curiosidade, adotado por grandes entidades:

[Google - Projetos em C/C++ (Chrome, e entre outros)](https://google.github.io/styleguide/cppguide.html#Conditionals)

[Gnome - Linux - Projetos em C](https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en)

**Comment by heliopn** [comment]
Ok! Obrigado pela dica valiosa Du, já li os papers! Irei fazer as alterações e prestar mais atenção à esses detalhas.
