### ISSUE TITLE
Não é necessário usar pio_set_input neste caso.

### ISSUE THREAD

**Issue by eduardomarossi** [slimkaki/APS1-Embarcados#6]
https://github.com/slimkaki/APS1-Embarcados/blob/f4328b2bc7f28c5860b09de09f1802193f1fd6cd/src/main.c#L253-L270

Como em seguida você usa o pio_configure com a flag PIO_INPUT, não é necessário usar o pio_set_input, já que faz a mesma coisa.

**Comment by heliopn** [comment]
Ok! Já irei fazer a mudança aqui, Du!
