### ISSUE TITLE
Grandes vetores constantes de dados

### ISSUE THREAD

**Issue by eduardomarossi** [slimkaki/APS1-Embarcados#7]
https://github.com/slimkaki/APS1-Embarcados/blob/f4328b2bc7f28c5860b09de09f1802193f1fd6cd/src/musicas.h#L142-L170

No arquivo musicas.h existem diversos vetores com informações constantes (uma vez definido, nunca é alterado). 

Uma grande recomendação de quando trabalhamos com sistemas embarcados, e também acaba sendo uma excelente prática de programação, sempre que tivermos dados constantes que não alteram (imutáveis), declarar eles com a propriedade **const**.

Exemplo:
```
const int pirate_tempo[] = ...
```

Quais as vantagens para um sistema embarcado?
Bom, o nosso SAME70, é uma CPU com 2048KB de ROM e 384KB de RAM [(fonte)](https://www.microchip.com/wwwproducts/en/ATSAME70Q21) Quando você não utiliza a propriedade **const**, o compilador assume, que o vetor pode ser alterado a qualquer instante, por este motivo, ele é armazenado na RAM do processador. Agora, com o **const**, estes dados serão armazenados na ROM! Já que eles não se alteram! Dando uma enorme economia de memória RAM. 

Lembre-se que geralmente em sistemas embarcados, um dos maiores gargalos é a quantidade de memória RAM disponível (RAM = custo = aumenta preço).

**Comment by heliopn** [comment]
Ok! Não sabia desse fato, Du! Não vou mais errar com relação a isso!
